create database library;

use library;

create table author(
  id int not null primary key auto_increment,
  first_name varchar(255),
  last_name varchar(45),
  biography text
) ENGINE = InnoDB;

create table publisher(
  id int not null primary key auto_increment,
  first_name varchar(100),
  last_name varchar(100),
  email varchar(45)
) ENGINE = InnoDB;

create table borrower(
  cardNo varchar(16) not null primary key,
  first_name varchar(45),
  last_name varchar(45),
) ENGINE = InnoDB;

create table library_branch (
  id int not null primary key auto_increment,
  name varchar(100),
  adress varchar(255)
) ENGINE = InnoDB;

create table book (
  id int not null primary key auto_increment,
  title varchar(255) ,
  publisher_id int,
  author_id int
) ENGINE = InnoDB;

create table book_copies( 
  id int not null primary key auto_increment,
  book_id int, 
  library_branch_id int, 
  no_of_copies int
) ENGINE = InnoDB;

create table book_loans (
  id int not null primary key auto_increment,
  library_branch_id int,
  borrower_cardNo varchar(16),
  book_id int,
  date_out datetime,
  due_date datetime
) ENGINE=InnoDB;



// Insertion des auteurs dans la table author 

INSERT INTO "author" ("first_name","last_name")
VALUES
    ('Bravi', 'Soledad'),
    ('Brière', 'Haquet Alice'),
    ('Van', 'Zeveren Michel'),
    ('Crozon', 'Alain'),
    ('Chedru', 'Delphine'),
    ('Collectif', ''),
    ('Mbodj', 'Souleymane'),
    ('Cassabois', 'Jacques'),
    ('Uzunoglu', 'Adelheid'),
    ('Grousset', 'Alain'),
    ('Mounié', 'Didier'),
    ('Fromental', 'Jean-Luc'),
    ('Sellier', 'Marie'),
    ('Orizet', 'Jean'),
    ('Renault', 'Jean'),
    ('Rachmuhl', 'Françoise'),
    ('Giraud', 'Robert'),
    ('Beamri', 'R'),
    ('Coppin', 'Brigitte'),
    ('Muzi', 'Jean'),
    ('Douzou', 'Olivier'),
    ('Carter', 'David A.'),
    ('Fox', 'Mem'),
    ('Piquemal', 'Michel'),
    ('Solet', 'Bertrand'),
    ('Dedieu', 'Thierry'),
    ('Barrier', 'Perceval'),
    ('Letuffe', 'Anne'),
    ('Boyer', 'Cécile'),
    ('Bloch', 'Muriel'),
    ('Jalbert', 'Philippe'),
    ('Rettich', 'Maget'),
    ('Pomme', 'd\'api'),
    ('Buson', ''),
    ('Touquet', 'Marie'),
    ('Grimm', 'Jacob'),
    ('Kimura', 'Ken'),
    ('Ponti', 'Claude'),
    ('Haughton', 'Chris'),
    ('Browne', 'Anthony'),
    ('Gutman', 'claude'),
    ('Chaty', 'Guy'),
    ('Friot', 'Bernard'),
    ('Bonbon', 'Cécile'),
    ('Siméon', 'Jean'),
    ('Schubiger', 'Jürg'),
    ('Perrin', 'Clotilde'),
    ('Favret', 'Hafida'),
    ('Grosléziat', 'Chantal'),
    ('Jean', 'Georges'),
    ('Sara', ''),
    ('Jun', 'Takabataka'),
    ('Le', 'Touzé'),
    ('Khoury-Ghata', 'Vénus'),
    ('Louchard', 'Antonin'),
    ('James', 'Simon'),
    ('Devernois', 'Elsa'),
    ('Coat', 'Anik'),
    ('Beigel', 'Christine'),
    ('Galeron', 'Henri'),
    ('Moniz', 'Madalena'),
    ('Feiffer', 'Jules'),
    ('Kogjan', 'Grégoire'),
    ('Boutros', 'Al-maari'),
    ('Laurent', 'Nathalie'),
    ('Houdart', 'Emmanuelle'),
    ('Adam', 'Olivier'),
    ('Gravel', 'Elise'),
    ('Ungerer', 'Tomi'),
    ('Guyennon', 'Duchêne'),
    ('Chaud', 'Benjamin'),
    ('Corenblit', 'Rachel'),
    ('Cali', 'Davide'),
    ('Rodari', 'Gianni'),
    ('Corentin', 'Philippe'),
    ('Jean', 'Didier'),
    ('Goffin', 'Josse'),
    ('Duras', 'Marguerite'),
    ('Serres', 'Alain'),
    ('Vatinel', 'Pascal'),
    ('Morgan', ''),
    ('Guilloppé', 'Antoine'),
    ('Norac', 'Carl'),
    ('Bruel', 'Christian'),
    ('CRILJ', ''),
    ('Van', 'der'),
    ('Fred', 'L'),
    ('Carroll', 'Lewis'),
    ('Willis', 'Jeanne'),
    ('Crowther', 'Kitty'),
    ('Gourounas', 'Jean'),
    ('Bourre', 'Martine'),
    ('Sadeler', 'Joël'),
    ('Bernard', 'Cécile'),
    ('Pacovska', 'Kveta'),
    ('Rosensthiel', 'Agnès'),
    ('Brami', 'Elisabeth'),
    ('Roman', 'Ghislaine'),
    ('Lacombe', 'Benjamin'),
    ('Krings', 'Anton'),
    ('Raschka', 'Chris'),
    ('Seyvos', 'Florence'),
    ('Rascal', ''),
    ('Moriceau', ''),
    ('Ben', 'Kemoun Hubert'),
    ('Taïeb', 'el Alj Ahmed'),
    ('Chraïbi', 'Driss'),
    ('Bauer', 'Jutta'),
    ('Ducos', 'Max'),
    ('Boucher', 'Michel'),
    ('Vaugelade', 'Anaïs'),
    ('Miège-Simansky', 'Denise'),
    ('Hédelin', 'Pascale'),
    ('Lacet', 'Yvonne'),
    ('Le', 'Hir'),
    ('Paoloni', 'Sonia'),
    ('Cathrine', 'Arnaud'),
    ('Conrad', 'Paul'),
    ('Escoffier', 'Michaël'),
    ('Browne', 'Anthony'),
    ('Solotareff', 'Grégoire'),
    ('Könnecke', 'Ole'),
    ('Fondation', 'Zakoura'),
    ('Charmeux', 'Evelyne'),
    ('Boujon', 'Claude'),
    ('Bouchard', 'André'),
    ('Fastier', 'Yann'),
    ('Carle', 'Eric'),
    ('Montardre', 'Hélène'),
    ('Hall', 'Kirsten'),
    ('Jonas', 'Anne'),
    ('Silverstein', 'Shel'),
    ('Troïanowski', 'Johan'),
    ('Queneau', 'Raymond'),
    ('Mari', 'Iela'),
    ('Vincensini', 'Paul'),
    ('Girardet', 'Sylvie'),
    ('Mau', 'Olivier'),
    ('Harcourt', 'Claire'),
    ('Coste', 'Nadia'),
    ('Zenzius', 'Pierre'),
    ('Lévy', 'Didier'),
    ('Dutruc-Rosset', 'Florence'),
    ('Ashbé', 'Jeanne'),
    ('Chic', 'Suzy'),
    ('Garralon', 'Claire'),
    ('Mathis', 'Jean-Marc'),
    ('Bruley', 'Marie-Claire'),
    ('Roxbee', 'Cox'),
    ('Salvi', 'Manuela'),
    ('Lejonc', 'Régis'),
    ('Chedid', 'Andrée'),
    ('Meunier', 'Henri'),
    ('Delye', 'Pierre'),
    ('Albert', 'Adrien'),
    ('Hugo', 'Victor'),
    ('Rathman', 'Peggy'),
    ('Poussier', 'Audrey'),
    ('Ramos', 'Mario'),
    ('Tanaka', 'Béatrice'),
    ('Agopian', 'Annie'),
    ('Varley', 'Susan'),
    ('Eeckhout', 'Emmanuelle'),
    ('Ramadier', ''),
    ('Lewis', 'Jean-Patrick'),
    ('Cadot', 'Colin'),
    ('Bourgeau', 'Vincent'),
    ('Van', 'Hout'),
    ('Doray', 'Malika'),
    ('Van', 'der'),
    ('Horowitz', 'Anthony'),
    ('Pinson', 'Zaza'),
    ('Sadat', 'Mandana'),
    ('Mollet', 'Charlotte'),
    ('Jadoul', 'Emile'),
    ('Paris', 'Hugues'),
    ('Pommaux', 'Yvan'),
    ('Chérer', 'Sophie'),
    ('Minhos', 'Martins'),
    ('Godeau', 'Vincent'),
    ('Cristina', 'Henriqueta'),
    ('Cone', 'Bryant'),
    ('Kerloc\'h', 'Jean'),
    ('Twain', 'Mark'),
    ('Ocelot', 'Michel'),
    ('Banks', 'Kate'),
    ('Aceval', 'Nora'),
    ('Thomas', 'Valérie'),
    ('Surget', 'Alain'),
    ('Le', 'Clézio'),
    ('Mourlevat', 'Jean'),
    ('Yeh', 'Chun-Liang'),
    ('Clément', 'Claude'),
    ('Pennart', 'Geoffroy'),
    ('John', 'Jory'),
    ('Dellamarre', 'Bellego'),
    ('Promeyrat', 'Coline'),
    ('Prévert', 'Jacques'),
    ('Blake', 'Quentin'),
    ('Lecointre', 'Jean'),
    ('Baer', 'Julien'),
    ('Van', 'Laan'),
    ('Ellwand', 'David'),
    ('Kang', 'Hye-sook'),
    ('Dumont', 'Jean-François'),
    ('Waddell', 'Martin'),
    ('Leprince', 'de'),
    ('Pef', ''),
    ('Lecaye', 'Alexis'),
    ('David', 'Gauthier'),
    ('David', 'François'),
    ('Elzbieta', ''),
    ('Deacon', 'Alexis'),
    ('Frier', 'Raphaële'),
    ('Barroux', ''),
    ('Cantais', 'Claire'),
    ('Nottet', 'Pascal'),
    ('Chen', 'Chih-Yuan'),
    ('Gouichoux', 'René'),
    ('Valckx', 'Catharina'),
    ('Ahlberg', 'Janet'),
    ('Hoban', 'Tana'),
    ('Perrault', 'Charles'),
    ('Grimm', 'Jakob'),
    ('Kasano', 'Yuchi'),
    ('Marais', 'Frédéric'),
    ('Le', 'Saux'),
    ('Lear', 'Edward'),
    ('Kuo', 'Fifi'),
    ('Crausaz', 'Anne'),
    ('Monari', 'Manuela'),
    ('Fort', 'Paul'),
    ('Morgenstern', 'Susie'),
    ('Géhin', 'Elisa'),
    ('Berner', 'Rotraut'),
    ('Dwell', 'Studio'),
    ('Ginsburg', 'Mirra'),
    ('Hutchins', 'Pat'),
    ('Hirsching', 'Nicolas'),
    ('Emberley', 'Ed'),
    ('Hill', 'Eric'),
    ('Grenier', 'Christian'),
    ('Lenain', 'Thierry'),
    ('Scotto', 'Thomas'),
    ('Weninger', 'Brigitte'),
    ('Cissé', 'Mamadou'),
    ('Valentin', 'Elsa'),
    ('Hahn', 'Cyril'),
    ('Matéo', '"Pepito,"'),
    ('Parot', 'Annelore'),
    ('Celli', 'Rose'),
    ('Servant', 'Stéphane'),
    ('Soutif', 'François'),
    ('Folika', ''),
    ('Jalibert', 'Maria'),
    ('Victor', 'Sylvain'),
    ('Courgeon', 'Rémi'),
    ('Herbauts', 'Anne'),
    ('Martin', 'Bill'),
    ('Bataille', 'Marion'),
    ('Zarcate', 'Catherine'),
    ('Veille', 'Eric'),
    ('Silei', 'Fabrizio'),
    ('Herbreteau', 'Gaston'),
    ('Diallo', 'Boubacar'),
    ('Manceau', 'Edouard'),
    ('Coat', 'Janik'),
    ('Henry', 'Jean-Marie'),
    ('Zemach', 'Margot'),
    ('Blake', 'Stéphanie'),
    ('Dreyfuss', 'Corinne'),
    ('Cousins', 'Lucy'),
    ('Goossens', 'Philippe'),
    ('Latyk', 'Olivier'),
    ('Denolle', 'Christel'),
    ('Adams', 'Pam'),
    ('Monloubou', 'Claire'),
    ('Konaté', 'Moussa'),
    ('Loyer', 'Anne'),
    ('Grave', 'Marie-Eve'),
    ('Cvach', 'Milos'),
    ('Gay', 'Michel'),
    ('Stehr', 'Frédéric'),
    ('Yonezu', 'Yusuke'),
    ('Kochka', ''),
    ('Voltz', 'Christian'),
    ('Brunet', 'Bénédicte'),
    ('Mélisou', 'Marie'),
    ('Van', 'Genechten'),
    ('Nakamura', 'Junko'),
    ('Klassen', 'Jon'),
    ('Ribeyron', 'Samuel'),
    ('Willems', 'Mo'),
    ('Andersen', 'Hans'),
    ('Carlain', 'Noé'),
    ('Grégoire', 'Caroline'),
    ('Khaldi-Bonnaud', 'Ahmed'),
    ('Turin', 'Joëlle'),
    ('Bisinski', 'Pierrick'),
    ('Lexau', 'Joan'),
    ('Dorléans', 'Marie'),
    ('Pittau', 'Francesco'),
    ('Lestrade', 'Agnès'),
    ('Giordano', 'Philip'),
    ('Bizouerne', 'Gilles'),
    ('Tallec', 'Olivier'),
    ('Brisou', 'Pellen'),
    ('Dexet', 'Hector'),
    ('Smith', 'Lane'),
    ('Zolotow', 'Charlotte'),
    ('Le', 'Craver'),
    ('Cumont', 'Louise-Marie'),
    ('Césaire', 'Aimé'),
    ('Sheldon', 'Dyan'),
    ('Gudule', ''),
    ('Malte', 'Marcus'),
    ('Nadja', ''),
    ('Fuentes', 'Roland'),
    ('Cousseau', 'Alex'),
    ('Rosen', 'Michael'),
    ('Angeli', 'May'),
    ('Kimiko', ''),
    ('Dr', 'Seuss'),
    ('Pianina', 'Vincent'),
    ('Poe', 'Edgar'),
    ('Cortey', 'Anne'),
    ('Simonsen', 'Michèle'),
    ('Tsarfati', 'Einat'),
    ('Longour', 'Michèle'),
    ('Fersen', 'Thomas'),
    ('Quatromme', 'France'),
    ('Duval', 'Elisabeth'),
    ('Chazerand', 'Emilie'),
    ('Gravett', 'Emily'),
    ('Gabriel', 'Pierre'),
    ('Kiffer', 'Christine'),
    ('Davies', 'Stephen'),
    ('Grindley', 'Sally'),
    ('Bertrand', 'Frédérique'),
    ('Cadier', 'Morgane'),
    ('Minfong', 'Ho'),
    ('Painset', 'Marie-France'),
    ('Alemagna', 'Béatrice'),
    ('Tullet', 'Hervé'),
    ('Griffon', 'A'),
    ('Bricout', 'Bernadette'),
    ('Devos', 'Lydia'),
    ('Monfreid', 'Dorothée'),
    ('Nicolas', 'Christophe'),
    ('Guérif', 'Andy'),
    ('Wlodarczyk', 'Isabelle'),
    ('Dorin', 'Philippe'),
    ('Chabas', 'Jean-François'),
    ('Mélano', 'Olivier'),
    ('Morin', 'Patrick'),
    ('Daniau', 'Marc'),
    ('Shulevitz', 'Uri'),
    ('Vidal', 'Séverine'),
    ('Kipling', 'Rudyard'),
    ('Fehr', 'Daniel'),
    ('Vivardi', 'Liuna'),
    ('Cosneau', 'Olivia'),
    ('Pereira', 'Marjolaine'),
    ('Dé', 'Claire'),
    ('Tardieu', 'Jean'),
    ('Havard', 'Christian'),
    ('Coran', 'Pierre'),
    ('Dumas', 'Philippe'),
    ('Yzac', 'Adeline'),
    ('Lü', 'Yuan'),
    ('Cevin', 'Evelyne'),
    ('Ionesco', 'Eugène'),
    ('Gaussel', 'Alain'),
    ('Belhalfaoui', 'Hamou'),
    ('Gougaud', 'Henri'),
    ('Féron', 'Romano'),
    ('Causse', 'Rolande'),
    ('Gendrin', 'Catherine'),
    ('Gripari', 'Pierre'),
    ('Cadier', 'Florence'),
    ('Musa', 'Hassan'),
    ('Condominas', 'Baptiste'),
    ('Laporte', 'Michel'),
    ('Guillaume', 'Olive'),
    ('Darwiche', 'Jihad'),
    ('Delpeuch', 'Régis'),
    ('"Bryan,"', '"Muzi,"'),
    ('Faraggi', 'Anne'),
    ('Sternberg', 'Jacques'),
    ('Mayo', 'Margaret'),
    ('Descamps', 'Dominique'),
    ('Mezquita', 'Roberto'),
    ('Bertrand', 'Pierre'),
    ('UG', 'Philippe'),
    ('Allancé', 'Mireille'),
    ('Brun', 'Cosme'),
    ('Torres', 'Cimarusti'),
    ('Kérillis', 'Hélène'),
    ('Gil', 'Isabelle'),
    ('Dahl', 'Roald'),
    ('Schädlich', 'Hans'),
    ('Barthélémy', 'Mimi'),
    ('Craipeau', 'Jean-Loup'),
    ('Marie', 'et'),
    ('London', 'Jack'),
    ('Roubaud', 'Jacques'),
    ('Nickl', 'Peter'),
    ('Sendak', 'Maurice'),
    ('Bouteloup', 'Philippe'),
    ('"Kochka,"', 'd\'après'),
    ('Grimm', 'Jakob'),
    ('Kunhardt', 'Dorothy'),
    ('Boisrobert', 'et'),
    ('Perreault', 'Mélanie'),
    ('Grosz', 'Pierre'),
    ('Massini', 'Anaïs'),
    ('Tamarin', 'Annette'),
    ('Marceau', 'Fani'),
    ('Roumiguière', 'Cécile'),
    ('Martin', 'Simon'),
    ('Alline', 'Christophe'),
    ('Eluard', 'Paul'),
    ('Mbaye', 'Ndaak'),
    ('Bauer', 'Marion'),
    ('Tawa', 'Kouam'),
    ('Holzwarth', 'Werner'),
    ('Gunzig', 'Thomas'),
    ('Teckentrup', 'Britta'),
    ('Defourny', 'Michel'),
    ('Baronian', 'Jean-Baptiste'),
    ('Ramstein', 'Anne-Margot'),
    ('Sanders', 'Alex'),
    ('Costes', 'Olivier'),
    ('Perrin', 'Julien'),
    ('Gendre', 'Nathalie'),
    ('Leblanc', 'Catherine'),
    ('Claveloux', 'Nicole'),
    ('Weiss', 'Anne'),
    ('Poslaniec', 'Christian'),
    ('Rateau', 'Dominique'),
    ('Cathalo', 'Georges'),
    ('Bachelet', 'Gilles'),
    ('Detamlbel', 'Régine'),
    ('Nadaud', 'Claire'),
    ('Dubost', 'Louis'),
    ('Simler', 'Isabelle'),
    ('Vian', 'Boris'),
    ('Carminati', 'Chiara'),
    ('Bertier', 'Anne'),
    ('Pochard', 'Mireille'),
    ('Lacor', 'Agnès'),
    ('Scelles', 'Millie'),
    ('Wormell', 'Chris'),
    ('Kowarsky', 'Didier'),
    ('Leo', 'Patrice'),
    ('Kerloc\'h', 'Jean-Pierre'),
    ('Major', 'Lenia'),
    ('Dubuc', 'Marianne'),
    ('Laâbi', 'Jocelyne'),
    ('Mac', 'Bratney'),
    ('Muller', 'Gerda'),
    ('Armellini', 'Chiara'),
    ('Dang', 'Khoa'),
    ('Sall', 'Mamadou'),
    ('Green', 'Ilya'),
    ('Roland', 'Claudine'),
    ('Barton', 'Byron'),
    ('Malineau', 'Jean'),
    ('M', 'Serres'),
    ('Gutleben', 'Muriel'),
    ('Frasson-Cochet', 'Agathe'),
    ('Tixier', 'Jean'),
    ('Brown', 'Ruth'),
    ('Erlbruch', 'Wolf'),
    ('Cognet', 'Lilas'),
    ('Brunelet', 'Madeleine'),
    ('Lilienthal', 'Henri'),
    ('Villard', 'Marc'),
    ('Kitzing', 'Constanze'),
    ('Leynaud', 'Johan'),
    ('Vignal', 'Hélène'),
    ('Yeoman', 'John'),
    ('Soupault', 'Philippe'),
    ('Ivanovitch', 'Lair'),
    ('Delval', 'Marie'),
    ('Joly', 'Fanny'),
    ('Legrand', 'Marie'),
    ('Jandl', 'Ernst'),
    ('Steig', 'William'),
    ('Mathis', ''),
    ('Guillbaud', 'Luce'),
    ('Marsol', 'Manuel'),
    ('Tenor', 'Arthur'),
    ('Burningham', 'John'),
    ('Knowles', 'Sheena'),
    ('Proeng', 'Pich'),
    ('Kebrety', 'Maryam'),
    ('Rutten', 'Mélanie'),
    ('Leroy', 'Hélène'),
    ('Mac', 'Kee'),
    ('Petit', 'Michèle'),
    ('Cuvellier', 'Vincent'),
    ('Yolen', 'Jane'),
    ('Tae-Jun', 'Lee'),
    ('Clément', 'Claire'),
    ('Brulet', 'Gilles'),
    ('Vast', 'Emilie'),
    ('Gellé', 'Albane'),
    ('Hakim', 'Miloud'),
    ('Davies', 'Benji'),
    ('Roy', 'Claude'),
    ('Du', 'Faÿ'),
    ('Bruley', 'M.'),
    ('Kiko', ''),
    ('Sénégas', 'Stéphane'),
    ('Battut', 'Eric'),
    ('Vincent', 'Gabrielle'),
    ('Joie', 'par'),
    ('Obin', 'Manfeï'),
    ('Nadaus', 'Roland'),
    ('Maubille', 'Jean'),
    ('Pfeiffer', 'Virginie'),
    ('Collectif', 'enfants'),
    ('Stella', 'Gaia'),
    ('Hole', 'Stian'),
    ('Van', 'der'),
    ('Pennac', 'Daniel'),
    ('Fontenaille', 'Elise'),
    ('Lobel', 'Arnold'),
    ('Poirot-Chérif', 'Sandra'),
    ('Slater', 'Dashka'),
    ('Pintus', 'Eric'),
    ('Ohmura', 'Tomoko'),
    ('Iwamura', 'Kazuo'),
    ('Dubray', 'Anne-Thérèse'),
    ('Minne', 'Brigitte'),
    ('Lacasa', 'Gomez'),
    ('Desplat-Duc', 'Anne-Marie'),
    ('Bessard', 'Sylvie'),
    ('Szac', 'Murielle'),
    ('Joire', 'Françoise'),
    ('Place', 'François'),
    ('Goble', 'Paul'),
    ('Pelot', 'Dylan'),
    ('McDermott', 'Gerald'),
    ('Leroy', 'Jean'),
    ('Bertron', 'Martin'),
    ('Fugier', 'Laurence'),
    ('Verdelet-Lamare', 'Annie'),
    ('Heurté', 'Yves'),
    ('Godard', 'Alex'),
    ('Mounier', 'Fabienne'),
    ('Stehr', 'Gérald'),
    ('Lionni', 'Leo'),
    ('Doremus', 'Gaëtan'),
    ('Baret', 'Idatte'),
    ('Nicodème', 'Béatrice'),
    ('Ouyessad', 'Myriam'),
    ('Lang', 'Suzanne'),
    ('Chen', 'Jiang'),
    ('Strasser', 'Susanne'),
    ('Hoestlandt', 'Jo'),
    ('Greef', 'Sabine'),
    ('Hudrisier', 'Cécile'),
    ('Noguès', 'Jean-Côme'),
    ('Hikmet', 'Hazim'),
    ('Bonnet', ''),
    ('Amrouche', 'Taos'),
    ('Astolfi', 'Claire'),
    ('Lechermeier', 'Philippe'),
    ('Orsenna', 'Erik'),
    ('Fontanel', 'Béatrice'),
    ('Le', 'Gall'),
    ('Epin', 'Bernard'),
    ('Graves', 'Robert'),
    ('Bernard', 'Fred'),
    ('Kubler', 'Laurence'),
    ('Balpe', 'Anne'),
    ('Parlange', 'Adrien'),
    ('Zoboli', 'Giovanna'),
    ('Gastaut', 'Charlotte'),
    ('Bernstein', 'Galia'),
    ('Colombet', 'Julie'),
    ('Rossi', 'Annie'),
    ('Massenot', 'Véronique'),
    ('Elias', 'Jean'),
    ('Brown', 'Ken'),
    ('Van', 'de'),
    ('Durand', 'Jean'),
    ('Vidal', 'Francine'),
    ('Timmers', 'Leo'),
    ('Tolstoï', 'Alexis'),
    ('Muzo', ''),
    ('Guillevic', ''),
    ('Swift', 'Jonathan'),
    ('Collectif', 'écoliers'),
    ('Cros', 'Charles'),
    ('Lhomme', 'Sandrine'),
    ('Levine', 'Ellen'),
    ('Laffon', 'Martine'),
    ('Bailly', 'Maître'),
    ('Charlip', 'Rémy'),
    ('Brunhoff', 'Jean'),
    ('Diament', 'Nic'),
    ('Munari', 'Bruno'),
    ('Baltscheit', 'Martin'),
    ('Labourdique', 'Jacques'),
    ('Ben', 'Soussan'),
    ('Cameron', 'Ann'),
    ('Farilli', 'Elena'),
    ('Deneux', 'Xavier'),
    ('Heitz', 'Bruno'),
    ('Domergue', 'Agnès'),
    ('Dorémus', 'Gaétan'),
    ('Barrett', 'Judi'),
    ('Go', 'Hyejin'),
    ('Riddell', 'Chris'),
    ('Mayer', 'Mercer'),
    ('Trouillot', 'Evelyne'),
    ('Salisbury', 'Martin'),
    ('Neeman', 'Sylvie'),
    ('Lorant-Jolly', 'Annick'),
    ('Joffre', 'Véronique'),
    ('Attiogbé', 'Magali'),
    ('', ''),
    ('Estellon', 'Pascale'),
    ('Becker', 'Aaron'),
    ('Uman', 'Jennifer/Vidal'),
    ('Ruel', 'Adeline'),
    ('Nières-Chevrel', 'Isabelle'),
    ('Burgaud', 'Pierre'),
    ('Mercier', 'Julie'),
    ('Louzon', 'Camille'),
    ('Poitras', 'Anique'),
    ('Chèze', 'Bernard'),
    ('Baum', 'Gilles'),
    ('McKinnon', 'Heidi'),
    ('Mosconi', 'Patrick'),
    ('Thévenet', 'Séverine'),
    ('Marc', 'Solal'),
    ('De', 'Rockere'),
    ('Stevenson', 'RL'),
    ('Mezzalama', 'Chiara'),
    ('Palluy', 'Christine'),
    ('Pouyet', 'Marc'),
    ('Di', 'Mascio'),
    ('Donnio', 'Sylviane'),
    ('Guettier', 'Bénédicte'),
    ('Guillotte', 'Eric'),
    ('Geffen', 'Yehonatan'),
    ('Bayar', 'Michèle'),
    ('Mazard', 'Claire'),
    ('Thiès', 'Paul'),
    ('Havette', 'Servane'),
    ('Ross', 'Tony'),
    ('Moncomble', 'Gérard'),
    ('Misslin', 'Sylvie'),
    ('Baron', 'Marc'),
    ('Musa', 'Patricia'),
    ('Thiry', 'Marie-Eve'),
    ('Gypteau', 'Nadia'),
    ('Valckx', 'Catherine'),
    ('Delafosse', 'Claude'),
    ('Wagner', 'Jenny'),
    ('Sarno', 'Hélène'),
    ('Taback', 'Simms'),
    ('Charpentreau', 'Jacques'),
    ('Diaz', 'Marie'),
    ('Safirstein', 'Julie'),
    ('Hannappe', 'David'),
    ('Kanor', 'Fabienne'),
    ('Fine', 'Anne'),
    ('Wilsdorf', 'Anne'),
    ('Selena', 'Elena'),
    ('Bialestowski', 'Gérard'),
    ('Lautru', 'Michel'),
    ('Ibn', 'el'),
    ('Inkpen', 'Mick'),
    ('Lalinon', 'Gbado'),
    ('Boel', 'Anne'),
    ('Benjelloun', 'Saïd'),
    ('O\'Byrne', 'Nicola'),
    ('Delacroix', 'Sibylle'),
    ('François', 'André'),
    ('Nguyên', 'Viet'),
    ('Pinfold', 'Levi'),
    ('Cherisey', 'Thérèse'),
    ('Clavel', 'Bernard'),
    ('Kraus', 'Robert'),
    ('Lecaye', 'Olga'),
    ('Dros', 'Imme'),
    ('Kessler', 'Frédéric'),
    ('Berchoud', 'Bruno'),
    ('Held', 'Jacqueline'),
    ('Fortier', 'Natali'),
    ('Pinkey', 'Jerry'),
    ('Chenouf', 'Yvanne'),
    ('Boulaire', 'Cécile'),
    ('Escarpit', 'Denise'),
    ('Claverie', 'Jean'),
    ('Louis', 'Catherine'),
    ('Khémir', 'Nacer'),
    ('Harrison', 'David'),
    ('Duprat', 'Guillaume'),
    ('Berner', 'Rotraut'),
    ('Bonnafé', 'Marie'),
    ('Buguet', 'Anne'),
    ('Bernos', 'Clotilde'),
    ('Jaffrennou', 'Yves'),
    ('La', 'Fontaine'),
    ('Choux', 'Nathalie'),
    ('Robillard', 'Jean-Marie'),
    ('Picouly', 'Daniel'),
    ('S.A.H.G.Y.K.O.D.', ''),
    ('Lenglet', 'Maud'),
    ('Khoury', 'Gatha'),
    ('Mets', 'Alan'),
    ('Audren', ''),
    ('Hinckel', 'Florence'),
    ('Witek', 'Jo'),
    ('Mabanckou', 'Alain'),
    ('Nicolino', 'Fabrice'),
    ('Janisch', 'Hans'),
    ('Blanpain', 'Jean-Pierre'),
    ('Noiret', 'Gérard'),
    ('Ichikawa', 'Satomi'),
    ('Clément', 'Frédéric'),
    ('Utton', 'Peter'),
    ('Tashlin', 'Frank'),
    ('Moraes', 'Vinicius'),
    ('Swanson', 'Susan'),
    ('Moore', 'Inga'),
    ('Bielinsky', 'Claudia'),
    ('Joubert', 'Jean'),
    ('Moeyaert', 'Bart'),
    ('Laugausie', 'Justine'),
    ('Nivola', 'Claire'),
    ('Dorémus', 'Gaëtan'),
    ('Higgins', 'Ryan'),
    ('Zidrou', ''),
    ('Jaffé', 'Laura'),
    ('Maussion', 'Anne'),
    ('Bougeault', 'Pascale'),
    ('Carter', 'Noëlle'),
    ('Schneider', 'Christine'),
    ('Fournier', 'Jacques'),
    ('Glondoumé', 'Sika'),
    ('Diallo', 'Mamadou'),
    ('Cauwe', 'Lucie'),
    ('Colmont', 'Marie'),
    ('Daeninckx', 'Didier'),
    ('Aimé', 'Marcel'),
    ('Adriansen', 'Sophie'),
    ('Condominas', 'Laurent'),
    ('Rice', 'Hélène'),
    ('McNeil', 'David'),
    ('Watanabe', 'Michio'),
    ('Barbarou', 'Lucienne'),
    ('Perrin', 'Martine'),
    ('Yagoubi', 'Valérie'),
    ('Ruiz', 'Olivia'),
    ('Brenman', 'Ilan'),
    ('Korkos', 'Alain'),
    ('Lloyd', 'Sam'),
    ('Robberecht', 'Thierry'),
    ('Kalan', 'Robert'),
    ('Lagerlof', 'Selma'),
    ('Rueda', 'Claudia'),
    ('Ovide', ''),
    ('Aït', 'Ahmed'),
    ('Ebohéa', 'Marie'),
    ('Watanabe', 'Issa'),
    ('Flouw', 'Benjamin'),
    ('Diallo', 'Muriel'),
    ('Barman', 'Adrienne'),
    ('ARPLE', ''),
    ('Leduc', 'Daniel'),
    ('Pang', 'Miguel'),
    ('Kitamura', 'Satochi'),
    ('Laffon', 'Caroline'),
    ('Cantin', 'Marc'),
    ('Perret', 'Delphine'),
    ('Chabbert', 'Ingrid'),
    ('Bahar', 'Sunar'),
    ('Vernette', 'Véronique'),
    ('Titus', ''),
    ('Rouzé', 'Marina'),
    ('Fauliot', 'Pascal'),
    ('Mereu', 'Agata'),
    ('El', 'Fathi'),
    ('Schwarz', 'Annelies'),
    ('Ka', 'Olivier'),
    ('Vasconcelos', 'José'),
    ('Wisniewski', 'Gaya'),
    ('Demasse-Pottier', 'Stéphanie'),
    ('Kasza', 'Keiko'),
    ('Wall', 'Fiona'),
    ('Miyamoto', 'Tadao'),
    ('Legendre', 'Françoise'),
    ('Daufresne', 'Michelle'),
    ('Delecroix', 'Hanieh'),
    ('Silloray', ''),
    ('Zullo', 'Germano'),
    ('Claudel', 'Philippe'),
    ('Wiesner', 'David'),
    ('Cannard', 'Edmée'),
    ('Pegorier', 'Saralisa'),
    ('Gay-Para', 'Praline'),
    ('Bichonnier', 'Henriette'),
    ('Ayadi', 'Boubakeur'),
    ('Propp', 'Vladimir'),
    ('Léger-Cresson', 'Nathalie'),
    ('Boudet', 'Alain'),
    ('Guenoun', 'Joël'),
    ('Lecaye', 'Emmanuel'),
    ('Villiot', 'Bernard'),
    ('Desnouveaux', 'Florence'),
    ('Sommerset', 'Mark'),
    ('Golan', 'Haji'),
    ('Brouillard', 'Anne'),
    ('Kinsa', 'Gabriel'),
    ('Ben', 'Soussan'),
    ('Maunoury', 'Jean'),
    ('Weulersse', 'Odile'),
    ('Birant', 'Mehmet'),
    ('Charlat', 'Benoît'),
    ('Muratet', 'Louis'),
    ('Leblond', 'Michaël'),
    ('Beauvois', 'Delphine'),
    ('Olive', 'Guillaume'),
    ('Watt', 'Fiona'),
    ('Snicket', 'Lemony'),
    ('Mandelbaum', 'Pili'),
    ('Duval', 'Isabelle'),
    ('Hellings', 'Colette'),
    ('Bone', 'Betty'),
    ('Béziat', 'Julien'),
    ('Aribaud', 'Jean'),
    ('Jacques', 'Benoît'),
    ('Péghaire', 'Vincent'),
    ('Maudet', 'Mathieu'),
    ('Boisrobert', 'Anouck'),
    ('Beaude', 'PM.'),
    ('Sala', 'Felicita'),
    ('Bianco-Levin', 'Nicolas'),
    ('Ressouni', 'Demigneux'),
    ('Dayre', 'Valérie'),
    ('Cendrars', 'Blaise'),
    ('Stravinsky', 'Igor'),
    ('Poirot-Cherif', 'Sandra'),
    ('Bermond', 'Monique'),
    ('Vincent', 'François'),
    ('Roux', 'Julien'),
    ('Falconer', 'Ian'),
    ('Dunrea', 'Olivier'),
    ('Arrou-Vignod', 'Jean'),
    ('Jonquet', 'Thierry'),
    ('Simard', 'Eric'),
    ('Séguy', 'Fabienne'),
    ('Florian', 'Mélanie'),
    ('Rayna', 'S'),
    ('Norge', ''),
    ('Bunting', 'E.'),
    ('Doyle', 'Roddy'),
    ('Pizzoli', 'Greg'),
    ('Ravishankar', 'A'),
    ('Corazza', 'Linda'),
    ('Dupuy', 'Dunier'),
    ('Tupera', 'Tupera'),
    ('Alix', 'Cécile'),
    ('Yumoto', 'Kazumi'),
    ('Lavie', 'Oren'),
    ('Alonso', 'Jose'),
    ('Klausmeier', 'Klaus'),
    ('Di', 'Giovanni'),
    ('Ovaldé', 'Véronique'),
    ('Mrzyk', 'et'),
    ('Clavel', 'Fabien'),
    ('Texier', 'Ophélie'),
    ('Allen', 'Nicholas'),
    ('Touzeil', 'Jean'),
    ('Salinas', 'Veronica'),
    ('Le', 'Néouanic'),
    ('Helft', 'Claude'),
    ('Mwankumi', 'Dominique'),
    ('Desnos', 'Robert'),
    ('Ninie', ''),
    ('Dalrymple', 'Jennifer'),
    ('Sanders', 'Louis'),
    ('Loucou', 'Michel'),
    ('Dubois', 'CK'),
    ('Robert', 'Nadine'),
    ('Matéo', 'Pepito'),
    ('Monsabert', 'A.-Sophie'),
    ('Fournier', ''),
    ('Climo', 'Liz'),
    ('Giono', 'Jean'),
    ('Pinguilly', 'Yves'),
    ('Duve', 'Catherine'),
    ('Proust', 'Marcel'),
    ('Le', 'Saux'),
    ('Hugo', 'Hector'),
    ('Kamoun', 'Martine'),
    ('Macri', 'Giancarlo'),
    ('Duquennoy', 'Jacques'),
    ('Falorsi', 'Ilaria'),
    ('Saint-Exupéry', 'Antoine'),
    ('Verluca', 'Constance'),
    ('Mirman', 'Anne'),
    ('Wintrebert', 'Joëlle'),
    ('Allemand', 'Sylvie'),
    ('Weaver', 'Jo'),
    ('Chausson', 'Julia'),
    ('Carrier', 'Isabelle'),
    ('Grunelius-Hollard', 'Agnès'),
    ('Grunelius', 'Hollard'),
    ('Voutch', ''),
    ('Corr', 'Christopher'),
    ('Buteau', 'Gaëlle'),
    ('Jolibois', 'Christian'),
    ('Moüy', 'Iris'),
    ('Wood', 'Don'),
    ('Dubé', 'Pierrette'),
    ('Vinet', 'Sofie'),
    ('Aladjidi', 'Virginie'),
    ('Montse', 'Gisbert'),
    ('Holmelund', 'Minarik'),
    ('Dubois', 'Jean-Claude'),
    ('Hee-na', 'Baek'),
    ('Altan', ''),
    ('Destours', 'Christine'),
    ('Claire', 'Céline'),
    ('Dubois', 'Claude'),
    ('Tolstoï', 'Léon'),
    ('Iwamura', 'Kasuo'),
    ('Girardet', 'et'),
    ('Rogier', 'Françoise'),
    ('Pastoureau', 'Michel'),
    ('Oppel', 'Jean-Luc'),
    ('Rocard', 'Anne'),
    ('Jay', 'Françoise'),
    ('Brisac', 'Geneviève'),
    ('Backès', 'Michel'),
    ('Perez', 'Sébastien'),
    ('Bathany', 'Claude'),
    ('Pinto', 'Deborah'),
    ('Henderson', 'Kathy'),
    ('Pavlenko', 'Marie'),
    ('Barcilon', 'Marianne'),
    ('Moka', ''),
    ('Bergèse', 'Paul'),
    ('Soletti', 'Pierre'),
    ('Hérédia', 'Géraldine'),
    ('Magnier', 'Bernard'),
    ('Mardam-Bey', 'Farouk'),
    ('Arraga', 'de'),
    ('Lévêque', 'Valérie'),
    ('Grant', 'Joan'),
    ('Storr', 'Catherine'),
    ('Badescu', 'Ramona'),
    ('Soleil', 'Emilie'),
    ('Mari', 'Iela'),
    ('Sorman', 'Joy'),
    ('Vissière', 'Sophie'),
    ('Escudié', 'René'),
    ('Loufane', ''),
    ('Coran', 'Pierre'),
    ('Da', 'Silva'),
    ('Pierpont', 'Nathalie'),
    ('Hobson', 'Bruce'),
    ('Lila', 'Prap'),
    ('"Bonnafé,"', '"Cabrero,"'),
    ('Felix', 'Lucie'),
    ('Moissard', 'Boris'),
    ('Chausse', 'Sylvie'),
    ('Benameur', 'Jeanne'),
    ('Chen', 'Jian'),
    ('Curatolo', 'Justine'),
    ('La', 'Villefromoit'),
    ('Félix', 'Lucie'),
    ('Delessert', 'Etienne'),
    ('Naumann-Villemin', 'Christine'),
    ('Bettelheim', 'Bruno'),
    ('Bigot', 'Gigi'),
    ('Olten', 'Manuela'),
    ('Ubac', 'Claire'),
    ('Dek', 'Maria'),
    ('Gréban', 'Quentin'),
    ('Bonotaux', 'Gilles'),
    ('Cabrera', 'Jane'),
    ('Morel', 'François'),
    ('Ruillier', 'Jérôme'),
    ('Jenkins', 'Steve'),
    ('Joslin', 'Sesyle'),
    ('Machado', 'Ana'),
    ('Santini', 'Bertrand'),
    ('Gabrielle', 'Vincent'),
    ('Teyssèdre', 'Fabienne'),
    ('Aubrun', 'Claudine'),
    ('Périgot', 'Joseph'),
    ('Gratias', 'Claire'),
    ('Némo', 'et'),
    ('Bresner', 'Lisa'),
    ('Kemmeter', 'Philippe'),
    ('Trédez', 'Emmanuel'),
    ('Besnier', 'Michel'),
    ('Manfeï', 'Obin'),
    ('Daywalt', 'Drew'),
    ('Skarmeta', 'Antonio'),
    ('Alibeu', 'Géraldine'),
    ('Hayashi', 'Emiri'),
    ('Lucia', 'Scuderi'),
    ('Steff', ''),
    ('Quintane', 'Nathalie'),
    ('Bickford-Smith', 'Coralie'),
    ('Ducatteau', 'Florence'),
    ('Battault', 'Paule'),
    ('Char', 'René'),
    ('Janikovszky', 'Eva'),
    ('Luciani', 'Jean-Luc'),
    ('Brami', 'Elizabeth'),
    ('Sakaï', 'Komako'),
    ('Bonniol', 'Magali'),
    ('Rimbaud', 'Arthur'),
    ('Coran', '"Pierre,"'),
    ('Turin', 'Adela'),
    ('Sabbagh', 'Clémence'),
    ('Voigt', 'Marie'),
    ('Pourquié', 'Bernadette'),
    ('Cohen-Janca', 'Irène'),
    ('Roger', 'Marie'),
    ('Blexbolex', ''),
    ('Issa', ''),
    ('Cole', 'Babette'),
    ('Dio', 'Mohamed'),
    ('Dorin', 'Perrine'),
    ('Tzannes', ''),
    ('Mebs', 'Gudrun'),
    ('Sarrazin', 'Jean-Charles'),
    ('Matsuoka', 'Tatsuhide'),
    ('Hughes', 'Emily'),
    ('Aubert', 'Brigitte'),
    ('Todd-Stanton', 'Joe'),
    ('Trotereau', 'Anne'),
    ('Clayton', 'Junior'),
    ('Guibert', 'Françoise'),
    ('Koenig', 'Viviane'),
    ('Spier', 'Paul'),
    ('Monnereau', 'Michel'),
    ('Larreula', 'Enric'),
    ('Caylou', 'Véronique'),
    ('Stein', 'Mathilde'),
    ('Hindenoch', 'Michel'),
    ('Larizza', 'Olivier'),
    ('Schickel', 'Emilie'),
    ('Japon', ''),
    ('Bobe', 'Françoise'),
    ('Lambersy', 'Werner'),
    ('Paris', 'Cécile'),
    ('Crosbie', 'Duncan'),
    ('Cardon', 'Laurent'),
    ('Hoban', 'Kristy'),
    ('Van', 'de'),
    ('Pappa', 'Rodoula'),
    ('Herbert', 'Scott'),
    ('Roman', 'Nadia'),
    ('Coat', 'Janie'),
    ('Kipling/Chaliand', 'Gérard'),
    ('Cobb', 'Rebecca'),
    ('Epanya', 'Christian'),
    ('Ferrer', 'Nino'),
    ('Raisson', 'Gwendoline'),
    ('Naumann', 'Villemin'),
    ('Kerr', 'Judith'),
    ('Gagnon', 'Nathalie'),
    ('Lodge', 'Jo'),
    ('Willer', 'Thérèse'),
    ('Armange', 'Xavier'),
    ('Daladier', 'Nathalie'),
    ('Duda', 'Christian'),
    ('Morrison', 'Toni'),
    ('Elschner', 'Géraldine'),
    ('Wise', 'Brown'),
    ('Misraki', ''),
    ('Pernaudet', 'Christophe'),
    ('Agence', 'Quand'),
    ('Cooke', 'Trish'),
    ('Legrand', 'Gilbert'),
    ('Colombani', 'Laetitia'),
    ('Santangelo', 'Eugène'),
    ('Lafonta', 'Isabelle'),
    ('Van', 'Zeveren'),
    ('Vassallo', 'Rose-Marie'),
    ('Rivoal', 'Marine'),
    ('Dufresne', 'Didier'),
    ('Oster', 'Christian'),
    ('Pontavice', 'Clémentine'),
    ('Sanchez', 'Virginie'),
    ('Gueyfier', 'Judith'),
    ('Schnitzberger', 'Simon'),
    ('Galea', 'Claudine'),
    ('Urial', ''),
    ('Seeber', 'Dorothea'),
    ('Buzzeo', 'Toni'),
    ('Aubrun', 'Claude'),
    ('Benoist', 'Cécile'),
    ('Chavepeyer', 'I'),
    ('Supervielle', 'Jules'),
    ('Su', 'Dong'),
    ('Goytisolo', 'José'),
    ('Ipcar', 'Dahlov'),
    ('Cazals', 'Thierry'),
    ('Voake', 'Charlotte'),
    ('Yi', 'Gee'),
    ('Roux', 'Delphine'),
    ('Kaïteris', 'Constantin'),
    ('Cabaco', 'Silvia'),
    ('Nessmann', 'Philippe'),
    ('Simon', 'Quitterie'),
    ('Shingu', 'Susumu'),
    ('Crews', 'Donald'),
    ('Malnuit', 'Françoise'),
    ('Bertrand', 'Micheline'),
    ('Billiard', 'Jean-Michel'),
    ('Mallard', 'Marie-Constance'),
    ('Brière', 'Joëlle'),
    ('Henkes', 'Kevin'),
    ('Gibert', 'Bruno'),
    ('Garth', 'Williams'),
    ('Church', 'Caroline'),
    ('Devaux', 'Stéfany'),
    ('Kalioujny', 'Pauline'),
    ('Cagnard', 'Dominique'),
    ('Pigois', 'Melissa'),
    ('Alméras', 'Arnaud'),
    ('Hale', 'Nathan'),
    ('Lee', 'Suzy'),
    ('Merleau-Ponty', 'Claire'),
    ('Mankour', 'Mohamed'),
    ('Fetjö', 'Raphaël'),
    ('Guillon', 'Camille'),
    ('Angelou', 'Maya'),
    ('Bayard', 'Michèle'),
    ('Galvin', 'Michel'),
    ('Thydell', ''),
    ('Dumortier', 'David'),
    ('Blegvard', 'E'),
    ('Ollivier', 'Mikaël'),
    ('Seong-eun', 'Kim'),
    ('Van', 'Biesen'),
    ('Prévot', 'Franck'),
    ('Grelet', 'Isabella'),
    ('Gravel', 'François'),
    ('Dodeller', 'Sylvie'),
    ('Peynot', 'Patrick'),
    ('Whelan', 'Gloria'),
    ('Lee', 'Hyun-kyeong'),
    ('Derouen', 'Jean-Marc'),
    ('Diéterlé', 'Nathalie'),
    ('Dieterlé', 'Nathalie'),
    ('Zimet', 'Ben'),
    ('Ehlert', 'Lois'),
    ('Barbeau', 'Philippe');



// Insertion des éditeurs ; 

INSERT INTO "publisher" ("first_name")
VALUES
    ('A pas de loups'),
    ('A2MIMO'),
    ('ABC Melody'),
    ('ACCES'),
    ('Actes Sud'),
    ('Actes sud junior'),
    ('Aedis'),
    ('Albin Michel'),
    ('Albin Michel jeunesse'),
    ('Aldéran édition'),
    ('Alice'),
    ('Alice jeunesse'),
    ('Alkindi'),
    ('Almaterra'),
    ('Alyssa'),
    ('Amaterra'),
    ('AND'),
    ('ANLCI'),
    ('Après la lune jeunesse'),
    ('Assoc fr pour la lecture'),
    ('Assoc. Paris-musées'),
    ('Association Afflux'),
    ('Atelier du poisson soluble'),
    ('Atelier du poissson soluble'),
    ('Atelier du Scribe'),
    ('Auto production'),
    ('Autrement'),
    ('Autrement jeunesse'),
    ('Balivernes'),
    ('Balzane'),
    ('Bayard'),
    ('Bayard jeunesse'),
    ('Belin'),
    ('Belin jeunesse'),
    ('Belize'),
    ('Benoît Jacques'),
    ('Benoît Jacques Books'),
    ('bib.municip Paris'),
    ('Bibliothèque de Toulouse'),
    ('Bilboquet'),
    ('Biscoto'),
    ('BNF'),
    ('Bruno Doucey'),
    ('Bulles de savon'),
    ('Cadex'),
    ('Cahiers du CRILJ n° 10'),
    ('Cahiers du CRILJ n° 3'),
    ('Cahiers du CRILJ n° 4'),
    ('Cahiers du CRILJ n° 5'),
    ('Cahiers du CRILJ n° 7'),
    ('Cahiers du CRILJ n°8'),
    ('Calmann-Lévy'),
    ('Cambourakis'),
    ('Casterman'),
    ('Castor benjamin'),
    ('Castor poche'),
    ('Catalpas'),
    ('CCMDE'),
    ('Centre Georges Pompidou'),
    ('Cercle de la librairie'),
    ('Chan-Ok'),
    ('Cherche-midi'),
    ('Cheyne'),
    ('Cipango'),
    ('Circé'),
    ('Circonflexe'),
    ('CLAP Midi-Pyrénées'),
    ('Compagnie créative'),
    ('Cornélius'),
    ('Corps puce'),
    ('Courtes et longues'),
    ('Dapper'),
    ('De facto'),
    ('De la Martinière'),
    ('De la Martinière jeunesse'),
    ('Des Eléphants'),
    ('Des Idées et des Hommes'),
    ('Didier'),
    ('Didier jeunesse'),
    ('Dominique et cie'),
    ('Donner à voir'),
    ('Duculot Casterman'),
    ('Ecole Centre Montauban'),
    ('Ecole des loisirs'),
    ('Ed Corps Puce'),
    ('Ed Quart monde'),
    ('Ed. des Elephants'),
    ('Ed. des Elephants/Amnesty'),
    ('Ed. du Jasmin'),
    ('Edition des Monts'),
    ('Editions de la Balle'),
    ('Editions du Jasmin'),
    ('Education Nationale'),
    ('Elan vert'),
    ('Encore une fois'),
    ('ERES'),
    ('Escabelle'),
    ('Esperluète'),
    ('Etre'),
    ('Eyrolles'),
    ('Flammarion'),
    ('Flammarion jeunesse'),
    ('FLBLB'),
    ('Fleurus'),
    ('Flies France'),
    ('FOL de l\'Ardèche'),
    ('Folio junior'),
    ('Folle avoine'),
    ('Fond. BNP'),
    ('France Loisirs'),
    ('Frimousse'),
    ('GAEL'),
    ('Galeri Minyatür'),
    ('Gallimard'),
    ('Gallimard jeunesse'),
    ('Gautier-Languereau'),
    ('Grandir'),
    ('Grasset'),
    ('Grasset jeunesse'),
    ('Gros textes'),
    ('Gründ'),
    ('Gulf Stream'),
    ('Hachette'),
    ('Hachette jeunesse'),
    ('Hatier'),
    ('Hatier jeunesse'),
    ('Hatier poche'),
    ('Helium'),
    ('Hélium'),
    ('Hoëbeke'),
    ('Hong Fei'),
    ('Hongfei'),
    ('Il était deux fois'),
    ('Jean-Pierre Delarge'),
    ('Kalandraka'),
    ('Kate\'art'),
    ('Kid Pocket'),
    ('Kilowatt'),
    ('Kimane'),
    ('Krom Sakamapheap'),
    ('L\'agrume'),
    ('L\'art à la page'),
    ('L\'Edune'),
    ('L\'élan vert'),
    ('L\'Harmattan'),
    ('L\'Hydre'),
    ('L\'idée bleue'),
    ('L\'iroli'),
    ('La Bagnole'),
    ('La cabane sur le chien'),
    ('La compagnie Créative'),
    ('La Découverte poche'),
    ('La joie de lire'),
    ('La joie par les livres'),
    ('La maison est en carton'),
    ('La Martinière'),
    ('La Palissade'),
    ('La Pastèque'),
    ('La Renarde rouge'),
    ('La ville brûle'),
    ('Larousse'),
    ('Le baron perché'),
    ('Le cherche midi'),
    ('Le Dé bleu'),
    ('Le Farfadet bleu'),
    ('Le Genevrier'),
    ('Le Griffon bleu'),
    ('Le Jasmin'),
    ('Le Pommier'),
    ('Le port a jauni'),
    ('Le Rocher'),
    ('Le Sablier éditeur'),
    ('Le Sorbier'),
    ('Le Sorbier/Amnesty'),
    ('Le Trou de nez'),
    ('Le vengeur masqué'),
    ('Les 400 coups'),
    ('Les Arènes'),
    ('Les Cahiers de la Charte'),
    ('les éditions du mouton cerise'),
    ('Les fourmis rouges'),
    ('Les Grandes Personnes'),
    ('Les Grands Personnes'),
    ('Les p\'tits bérets'),
    ('Les papareils'),
    ('Lirabelle'),
    ('Lirabelle/Amnesty'),
    ('Lis avec moi'),
    ('Lito'),
    ('Little Urban'),
    ('Lo Païs d\'Enfance'),
    ('Magnard'),
    ('Magnard jeunesse'),
    ('Mango'),
    ('Mango jeunesse'),
    ('Margot'),
    ('Marsam'),
    ('MeMo'),
    ('Mic-Mac'),
    ('Michalon'),
    ('Michel Lafon'),
    ('Mijade'),
    ('Mila'),
    ('Mila éditions'),
    ('Milan'),
    ('Milan éducation'),
    ('Milan jeunesse'),
    ('Milan poche'),
    ('Millefeuilles'),
    ('Minedition'),
    ('Mini Syros'),
    ('Montreuil'),
    ('MØtus'),
    ('Mouton cerise'),
    ('Naïve'),
    ('Nathan'),
    ('Nathan jeunesse'),
    ('Nord-Sud'),
    ('Notari'),
    ('Nuinui'),
    ('OQO éditions'),
    ('Oskar'),
    ('Oskar jeunesse'),
    ('Où sont les enfants ?'),
    ('P\'tit cairn'),
    ('P\'tit Glénat'),
    ('Palette'),
    ('Paquet éditions'),
    ('Paris Bibliothèques'),
    ('Paris Musées'),
    ('Pastel'),
    ('PEMF'),
    ('PEMF ados'),
    ('Penguin books'),
    ('Père Fouettard'),
    ('Petit à petit'),
    ('Picquier jeunesse'),
    ('Pluie d\'étoiles'),
    ('Pluie d’étoiles'),
    ('Plume d\'Ocris'),
    ('Plume de carotte'),
    ('Poche'),
    ('Pocket'),
    ('Pocket jeunesse'),
    ('Pocket junior'),
    ('Pockett junior'),
    ('Point de suspension'),
    ('Points de Suspension'),
    ('Poisson soluble'),
    ('Pourquoi pas'),
    ('Présence production'),
    ('Privat'),
    ('Publisud'),
    ('Quart monde'),
    ('Quatre fleuves'),
    ('Québec'),
    ('Rageot'),
    ('Réciproques'),
    ('Réunion des musées nationaux'),
    ('Réunion musées nationaux'),
    ('Rêves bleus'),
    ('Ricochet'),
    ('Rivages'),
    ('Robert Laffont'),
    ('Rocher'),
    ('Rouegue'),
    ('Rouergue'),
    ('Rouge safran'),
    ('Rue du monde'),
    ('Ruisseaux d\'Afrique'),
    ('Saltimbanque'),
    ('Sarbacane'),
    ('Sarbacane/Amnesty'),
    ('SEDRAP'),
    ('SEDRAP jeunesse'),
    ('Seghers'),
    ('Seghers jeune bilingue'),
    ('Seuil'),
    ('Seuil jeunesse'),
    ('Soc et foc'),
    ('Sorbier'),
    ('Souchon-Garrigue Hélène'),
    ('Stock'),
    ('Syros'),
    ('Syros Jeunesse'),
    ('Syros/Amnesty'),
    ('Table ronde'),
    ('Talents hauts'),
    ('Tapori'),
    ('Thierry Magnier'),
    ('Tourbillon'),
    ('Touret'),
    ('Usborne'),
    ('Vents d\'ailleurs'),
    ('Verdier'),
    ('Versant Sud'),
    ('Vigot'),
    ('Vilo jeunesse'),
    ('Vives voix'),
    ('Walker Book'),
    ('Yanbow al Kitab'),
    ('Yomad'),
    ('Zone J.'),
    ('Zorba');


/* insertion des livres dans la table book ; */

